#!/bin/bash

# 🚀 Deploy MindMix+ to Cloud for 24/7 Availability
# This script deploys to Render.com (free tier)

echo ""
echo "🧠 MindMix+ - Cloud Deployment Guide"
echo "====================================="
echo ""
echo "For 24/7 availability, you need:"
echo ""
echo "OPTION 1 - Render.com (Recommended - FREE):"
echo "   1. Go to https://render.com"
echo "   2. Sign up for free"
echo "   3. Create new Web Service"
echo "   4. Connect your GitHub repo"
echo "   5. Build command: cd frontend-web && npm install && npm run build"
echo "   6. Start command: serve -s build -l 3000"
echo "   7. Your app will be LIVE 24/7!"
echo ""
echo "OPTION 2 - Vercel (Easier - FREE):"
echo "   1. Go to https://vercel.com"
echo "   2. Connect GitHub repo"
echo "   3. Auto-deploys"
echo "   4. Get HTTPS URL instantly!"
echo ""
echo "OPTION 3 - Keep Tunnel Running 24/7:"
echo "   Use pm2 to auto-restart tunnel:"
echo "   pm2 start keep_tunnel.js --name mindmix-tunnel"
echo ""
echo "OPTION 4 - Use ngrok (more stable than serveo):"
echo "   npx ngrok http 3000"
echo "   (Get persistent URL)"
echo ""

