services:
  # Backend API Service
  - type: web
    name: mindmix-backend
    rootDir: backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false  # Set this in Render dashboard
      - key: JWT_SECRET
        sync: false  # Set this in Render dashboard
      - key: OPENAI_API_KEY
        sync: false  # Set this in Render dashboard

  # Frontend Web Service  
  - type: web
    name: mindmix-frontend
    rootDir: frontend-web
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://mindmix-iuzf.onrender.com

